/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.MouseInfo;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.rmi.Naming;
import java.util.Date;

/**
 *
 * @author Darek
 */
public class IRCClient extends javax.swing.JFrame {

        private class MouseDistanceObtainer extends Thread {

        public void run() {

            while (true) {

                try {
                    IRCInterface remoteObject = (IRCInterface) Naming.lookup("//localhost:1099/Chat");
                    String mouseHistory = remoteObject.getMouseDistances();
                    jTextArea4.setText(mouseHistory);
                    jTextField2.setText(remoteObject.getBestMouseDistances());
                    double lastx = 0;
                    double lasty = 0;
                    double all = 0;
                    double cm;
                    double rankCm = 0;

                    while (true) {
                        Thread.sleep(100);
                        double distance = Math.sqrt(Math.pow(lastx - MouseInfo.getPointerInfo().getLocation().x, 2) + Math.pow(lasty - MouseInfo.getPointerInfo().getLocation().y, 2));
                        distance *= 100;
                        distance = Math.round(distance);
                        distance /= 100;
                        all = all + distance;
                        cm = all * 0.026458333;
                        cm *= 10;
                        cm = Math.round(cm);
                        cm /= 10;
                        String cms = Double.toString(cm) + " cm";
                        jLabel2.setText(cms);
                        if(rankCm < cm - 100)
                        {
                            rankCm = cm;
                            MouseRank mouseRank = new MouseRank(username, cm);
                            remoteObject.addMouseDistance(mouseRank);
                            mouseHistory = remoteObject.getMouseDistances();
                            jTextArea4.setText(mouseHistory);
                            jTextField2.setText(remoteObject.getBestMouseDistances());
                        }
                        lastx = MouseInfo.getPointerInfo().getLocation().x;
                        lasty = MouseInfo.getPointerInfo().getLocation().y;
                    }
                } catch (Exception e) {
                    System.out.println("Error: " + e.toString());
                }

            }

        }
    }
    
    private class HistoryObtainer extends Thread {

        private Date start_time;

        HistoryObtainer(Date start_time) {
            this.start_time = start_time;
        }

        public void run() {

            while (true) {

                try {
                    IRCInterface remoteObject = (IRCInterface) Naming.lookup("rmi://localhost:1099/Chat");
                    String history = remoteObject.read(start_time);
                    jTextArea1.setText(history);
                    HistoryObtainer.sleep(10);
                } catch (Exception e) {
                    System.out.println("Error: " + e.toString());
                }

            }

        }
    }
    private HistoryObtainer historyObtainer;
    private MouseDistanceObtainer mouseDistanceObtainer = new MouseDistanceObtainer();
    private IRCInterface chat;
    private String username = "";
    protected Date start_time = new Date();

    /**
     * Creates new form ChatClient
     */
    public IRCClient() {
        initComponents();

        setTitle("IRC");

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    chat.writeString("Użytkownik " + username + " opuścił kanał.");
                } catch (Exception ex) {
                    System.out.println("Error: " + ex.toString());
                }
                System.exit(0);
            }
        });

        username = javax.swing.JOptionPane.showInputDialog(null,
                "Identyfikacja użytkownika",
                "Podaj imię",
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        try {
            chat = (IRCInterface) Naming.lookup("rmi://localhost:1099/Chat");
            chat.writeString("Użytkownik " + username + " dołączył do kanału.");

            historyObtainer = new HistoryObtainer(start_time);
            historyObtainer.start();

            mouseDistanceObtainer = new MouseDistanceObtainer();
            mouseDistanceObtainer.start();
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        window = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        input = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane1.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        window.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        input.setViewportView(jTextArea2);

        submit.setText("Wyślij");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setText("Distance:");

        jLabel2.setText("0");

        jScrollPane2.setViewportView(jTextPane1);

        jTextField1.setText("jTextField1");

        jTextArea4.setColumns(20);
        jTextArea4.setEditable(false);
        jTextArea4.setRows(5);
        jScrollPane3.setViewportView(jTextArea4);
        jTextArea4.getAccessibleContext().setAccessibleName("");
        jTextArea4.getAccessibleContext().setAccessibleDescription("");
        jTextArea4.getAccessibleContext().setAccessibleParent(null);

        jLabel4.setText("The Best:");

        jTextField2.setEditable(false);

        jLabel5.setText("Recent:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(window)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(window, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input)
                            .addComponent(submit, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            chat.writeUser(username, jTextArea2.getText());
            jTextArea2.setText("");
        } catch (Exception e) {
            System.out.println("Error: " + e.toString());
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRCClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRCClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRCClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRCClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRCClient().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton submit;
    private javax.swing.JScrollPane window;
    // End of variables declaration//GEN-END:variables
}
